version: '3'
services:

  # The application 
  app:
    image: php:7.2-apache
    build:
      context: ./docker/app
      dockerfile: app.dockerfile
    container_name: app
    working_dir: /var/www/html
    links:
      - database
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_PORT=${DB_PORT}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=database
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - "${APP_PORT}:80"

  # The Database
  database:
    image: mysql:8.0
    container_name: app_database
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - app_database:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - TZ=${TZ}

# Names out volume
volumes:
  app_database:
    driver: local
