version: '3'
services:

  # The application 
  app:
    image: php:7.2-apache
    build:
      context: ./.cloud
      dockerfile: app.dockerfile
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    ports:
      - "81:80"

